ARMOR:
  title: 护甲图鉴
  icon: fluent-emoji-flat:safety-vest
  href: /gallery/armor
SWORD:
  title: 武器图鉴
  icon: fluent-emoji-flat:crossed-swords
  href: /gallery/sword
GEM:
  title: 宝石图鉴
  icon: fluent-emoji-flat:gem-stone
  href: /gallery/gem
JEWELERY:
  title: 饰品图鉴
  icon: fluent-emoji-flat:ring
  href: /gallery/jewelries