- title: 最新更新
  order: 1
  items:
    - title: v1.2.0 版本更新
      href: /latest/v1-2-0
      icon: fluent-emoji-flat:sparkles
      type: major
      order: 1
    - title: v1.1.5 补丁更新
      href: /latest/v1-1-5
      icon: fluent-emoji-flat:bug
      type: patch
      order: 2
    - title: v1.1.0 版本更新
      href: /latest/v1-1-0
      icon: fluent-emoji-flat:rocket
      type: minor
      order: 3
- title: 历史版本
  order: 5
  items:
    - title: v1.0.5 补丁更新
      href: /history/v1-0-5
      icon: fluent-emoji-flat:hammer-and-wrench
      type: patch
      order: 1
    - title: v1.0.0 正式版发布
      href: /history/v1-0-0
      icon: fluent-emoji-flat:tada
      type: release
      order: 2

