SKINDROP:
  title: 皮肤驿站
  icon: fluent-emoji-flat:shorts
  href: /tools/skindrop
DAMAGE:
  title: 伤害计算
  icon: fluent-emoji-flat:crossed-swords
  href: /tools/damage
MCAUTH:
  title: 正版验证
  icon: fluent-emoji-flat:bookmark
  href: /tools/mcauth
PALETTE:
  title: 彩色文本生成
  icon: fluent-emoji-flat:artist-palette
  href: /tools/palette